"""add leetcode_url field

Revision ID: 807f2ff0f9f9
Revises: ce5799b4f89d
Create Date: 2025-07-11 03:05:21.623142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '807f2ff0f9f9'
down_revision: Union[str, None] = 'ce5799b4f89d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'github_username')
    op.drop_column('users', 'github_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_token', sa.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('github_username', sa.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
