"""add leetcode fields

Revision ID: ce5799b4f89d
Revises: f73db689d327
Create Date: 2025-07-11 00:14:40.929518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce5799b4f89d'
down_revision: Union[str, None] = 'f73db689d327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = inspector.get_columns('users')
    if not any(col['name'] == 'leetcode_url' for col in columns):
        op.add_column('users', sa.Column('leetcode_url', sa.String(length=100), nullable=True, comment='完整的LeetCode个人主页URL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'leetcode_url')
    # ### end Alembic commands ###
