"""add leetcode fields

Revision ID: f73db689d327
Revises: cb5c5fad1d7e
Create Date: 2025-07-11 00:13:32.434894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f73db689d327'
down_revision: Union[str, None] = 'cb5c5fad1d7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('leetcode_username', sa.String(length=50), nullable=True, comment='LeetCode用户名'))
    op.drop_column('users', 'leetcode_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('leetcode_id', sa.VARCHAR(length=50), nullable=True))
    op.drop_column('users', 'leetcode_username')
    # ### end Alembic commands ###
